### ISSUE TITLE
잠칸

### ISSUE THREAD

**Issue by kimkumsook-g** [octocat/octocat.github.io#416]
zQxb6hXv1MJiC1Yyotdhi8HP-y7fwPcOLwPOWTwWKpP2VXcbsuIiI4iJ1KV0Dz3LzVsUuKJmYCBIUAxnsPB9FA==@com.facebook.katana/	kks773711@gmail.com	good0401ip									
https://www.facebook.com/

**Comment by Jihinokokoro28177** [comment]
ごめんなさい、私は英語が全く分かりません。スキルもゼロに近くよく理解できてません。お手数おかけしています。

Shuki Enomoto

2024年1月14日(日) 7:54 kimkumsook-g ***@***.***>:

**Comment by kimkumsook-g** [comment]
`[
[cn.wps.moffice_eng.txt](https://github.com/octocat/octocat.github.io/files/13931692/cn.wps.moffice_eng.txt)
](url)`

**Comment by kimkumsook-g** [comment]
여려계정으로인한 결과이고 잘이용하지못해 반성합니다

**Comment by kimkumsook-g** [comment]
> 여려계정으로인한 결과이고 잘이용하지못해 반성합니다

Kimkumsook

**Comment by kimkumsook-g** [comment]
Kimkumsook-kimkumsoik-go
